version: 0.0
os: linux
files:
  - source: /
    destination: /webapps/boapi
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: update_config.sh
      timeout: 15
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: checkaccess.sh
      timeout: 30