version: 0.0
os: linux
files:
  - source: /
    destination: /webapps/boapi
hooks:
#  BeforeInstall:
#    - location: scripts/install_dependencies.sh
#      timeout: 300
#      runas: root
  AfterInstall:
    - location: scripts/update_config.sh
      timeout: 15
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/checkaccess.sh
      timeout: 30